[package]
name = "lambdars"
version = "0.1.0"
edition = "2021"

[lib]
name = "lambdars"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.86"
#env_logger = "0.11.5"
#traced-test = "0.3.6"
tracing = "0.1"
tracing-subscriber = "0.3"
#tracing-test = "0.2.5"
