[package]
name = "lambdars"
version = "0.1.0"
edition = "2021"

[lib]
name = "lambdars"
path = "src/lib.rs"
proc-macro = true

[dependencies]
anyhow = "1.0.86"

lambdars_core = { path = "../lambdars-core" }